#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := spi

# frab wants this
EXTRA_CPPFLAGS := -DESP8266

include version_finder.mk

include $(IDF_PATH)/make/project.mk